name: csu1658-stats
channels:
  - conda-forge
  - defaults
dependencies:
  # Python Version
  - python=3.9

  # Core Scientific Computing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0

  # Data Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - plotly>=5.0.0

  # Jupyter Environment
  - jupyter
  - ipykernel
  - nbformat

  # Statistical Analysis
  - statsmodels>=0.12.0
  - scikit-learn>=1.0.0

  # Development Tools
  - black
  - flake8
  - pytest

  # Additional pip packages
  - pip
  - pip:
    - jupyter-contrib-nbextensions
    - sphinx-rtd-theme
